### ISSUE TITLE
File name with more than one dot ex. 8.182.07.04.2.tif

### ISSUE THREAD

**Issue by haldrigar** [lmotta/catalog-on-the-fly#1]
Hello.
I have a ortomap files, which has names like 8.182.07.04.2.tif. 

Loaded layer in QGIS has a name "8" 

I think, that you chceck extension od the file with first dot and cut name to first part.

**Comment by lmotta** [comment]
Thanks!
Sorry for huge delay.
I fixed this issue and migrate this plugin  to QGIS3.
